### ISSUE TITLE
Unable to 'print preview' any mech with the app

### ISSUE THREAD

**Issue by MIDAS74** [Solaris-Skunk-Werks/solarisskunkwerks#256]
running Java SE 8, updated it in my troubleshooting, when I'm clicking on the 'print preview' button, nothing happens, the app just doesn't acknowledge it
upon reinstalling it I also have noticed that it isn't asking for the master list file path

went into the SSW_Log.txt at SSW/Logs and this error is showing up in the log. 
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: setSelectedIndex: 2 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at ssw.printpreview.dlgPreview.<init>(dlgPreview.java:54)
	at ssw.gui.frmMain.mnuPrintPreviewActionPerformed(frmMain.java:14218)
	at ssw.gui.frmMain.btnPrintPreviewActionPerformed(frmMain.java:14225)
	at ssw.gui.frmMain.access$2200(frmMain.java:61)
	at ssw.gui.frmMain$35.actionPerformed(frmMain.java:5346)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

any clues?

**Comment by WEKarnesky** [comment]
Some troubleshooting question:

- What OS are you using?
- You mentioned reinstalling, was it working previously on this computer?
- What changes or updates have you made to the system since the last time it was working?

> upon reinstalling it I also have noticed that it isn't asking for the master list file path

This is likely unrelated do to storing settings separate from the install folder.

**Comment by MIDAS74** [comment]
-I'm using windows 10
-by uninstalling I mean just deleting the files and unzipping the .zip files from the 0.7.6 release again
-Regarding changes I made, I don't think I made any. I was using it the night before, but upon opening the app again try and view a mech today, I found that the key was unresponsive. 
is there any other details I am missing?
