### ISSUE TITLE
Turrets are not working.   

### ISSUE THREAD

**Issue by iblum1** [Solaris-Skunk-Werks/solarisskunkwerks#69]
**Describe the bug**
When I open a file with a turret in it I get an empty box.  if I select a turret in a mech without one the program becomes unusable until restarted.

**Desktop (please complete the following information):**
 - OS: windows 10
Java version 8

**Comment by WEKarnesky** [comment]
I am having trouble reproducing this.  Can you please provide more detail in your steps?

My test: I selected Experimental Tech, Dark Age, Inner sphere set movement to 5/8/5, Added two Bombast Lasers, allocated all of the jumpjets and lasers and it's still functional.
 
![image](https://user-images.githubusercontent.com/8506084/66408196-59f9e080-e9a3-11e9-995d-13d5d8aee02d.png)

**Comment by iblum1** [comment]
I'll send some screenshots tonight

**Comment by iblum1** [comment]
This Arana has a turret.



    On Tuesday, October 8, 2019, 01:54:19 PM CDT, Ira Blum <iblum1@yahoo.com> wrote:  
 
 I'll send some screenshots tonight 

Sent from my iPhone
On Oct 8, 2019, at 10:12 AM, William E. Karnesky <notifications@github.com> wrote:



I am having trouble reproducing this. Can you please provide more detail in your steps?

My test: I selected Experimental Tech, Dark Age, Inner sphere set movement to 5/8/5, Added two Bombast Lasers, allocated all of the jumpjets and lasers and it's still functional.

**Comment by WEKarnesky** [comment]
Okay, we tracked this to an issue that is specifically in the *widescreen* version.  Until a fix is posted, using the standard version is a workaround.

**Comment by WEKarnesky** [comment]
Backtrace:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at ssw.gui.frmMainWide.BuildChassisSelector(frmMainWide.java:684)
    at ssw.gui.frmMainWide.LoadMechIntoGUI(frmMainWide.java:10817)
    at ssw.gui.frmMainWide.mnuLoadActionPerformed(frmMainWide.java:10560)
    at ssw.gui.frmMainWide.access$16400(frmMainWide.java:72)
    at ssw.gui.frmMainWide$208.actionPerformed(frmMainWide.java:10044)
```

**Comment by iblum1** [comment]
thanks!!!!
    On Tuesday, October 8, 2019, 08:49:37 PM CDT, William E. Karnesky <notifications@github.com> wrote:  
 
 
Backtrace:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at ssw.gui.frmMainWide.BuildChassisSelector(frmMainWide.java:684)
    at ssw.gui.frmMainWide.LoadMechIntoGUI(frmMainWide.java:10817)
    at ssw.gui.frmMainWide.mnuLoadActionPerformed(frmMainWide.java:10560)
    at ssw.gui.frmMainWide.access$16400(frmMainWide.java:72)
    at ssw.gui.frmMainWide$208.actionPerformed(frmMainWide.java:10044)

**Comment by WEKarnesky** [comment]
[The fix has been published](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/v0.7.1)
